# Generated by Django 4.0.5 on 2022-06-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('family_members', models.IntegerField(default=0)),
                ('bio', models.TextField()),
                ('school_grade', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('class_overall', models.CharField(max_length=100)),
                ('dreams', models.CharField(max_length=255)),
            ],
        ),
    ]
