# Generated by Django 4.0.5 on 2022-06-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
