# Generated by Django 4.0.5 on 2022-06-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0002_child_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
