# Generated by Django 4.0.5 on 2022-06-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0005_donor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor',
            new_name='Profile',
        ),
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to='profiles/'),
        ),
    ]
