# Generated by Django 4.0.5 on 2022-06-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0006_rename_donor_profile_child_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='needs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='tunzapp.financialneed'),
        ),
    ]
