# Generated by Django 4.0.5 on 2022-06-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0007_child_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='needs',
            field=models.CharField(blank=True, choices=[('1', 'School Fees'), ('2', 'Books'), ('3', 'Upkeep'), ('4', 'Shoes')], max_length=1, null=True),
        ),
    ]
