# Generated by Django 4.0.5 on 2022-06-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0009_alter_child_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='financialneed',
            name='need_1',
        ),
        migrations.RemoveField(
            model_name='financialneed',
            name='need_2',
        ),
        migrations.RemoveField(
            model_name='financialneed',
            name='need_3',
        ),
        migrations.RemoveField(
            model_name='financialneed',
            name='need_4',
        ),
        migrations.RemoveField(
            model_name='financialneed',
            name='need_5',
        ),
        migrations.RemoveField(
            model_name='financialneed',
            name='need_6',
        ),
        migrations.AddField(
            model_name='financialneed',
            name='needs',
            field=models.CharField(choices=[('1', 'School Fees'), ('2', 'Upkeep'), ('3', 'Shoes'), ('4', 'Uniform')], default='School Fees', max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='child',
            name='needs',
        ),
        migrations.AddField(
            model_name='child',
            name='needs',
            field=models.ManyToManyField(to='tunzapp.financialneed'),
        ),
    ]
