# Generated by Django 4.0.5 on 2022-06-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0011_alter_financialneed_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialneed',
            name='needs',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
