# Generated by Django 4.0.5 on 2022-06-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0016_alter_child_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='donors',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributor', to='tunzapp.donor'),
        ),
        migrations.AlterField(
            model_name='child',
            name='fee_amount',
            field=models.IntegerField(default=20000),
        ),
    ]
