# Generated by Django 4.0.5 on 2022-06-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunzapp', '0017_child_donors_alter_child_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='donors',
            field=models.ManyToManyField(related_name='contributors', to='tunzapp.donor'),
        ),
    ]
